// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa-70dEY1SRRsJQK1UtuW0M8BaHmzYizs',
    appId: '1:681145363568:web:7267042adff411d12ad8b5',
    messagingSenderId: '681145363568',
    projectId: 'travel-planner-64439',
    authDomain: 'travel-planner-64439.firebaseapp.com',
    storageBucket: 'travel-planner-64439.firebasestorage.app',
    measurementId: 'G-WZ9BYME0GC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmiy_pe94aGNtPy0PjHMZu35oxhhLnHIA',
    appId: '1:681145363568:android:224c1cf2f242003a2ad8b5',
    messagingSenderId: '681145363568',
    projectId: 'travel-planner-64439',
    storageBucket: 'travel-planner-64439.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-I14h8GjEskLdTpQVuhZTMwO8AAeDCLY',
    appId: '1:681145363568:ios:ef52fd977ae85b512ad8b5',
    messagingSenderId: '681145363568',
    projectId: 'travel-planner-64439',
    storageBucket: 'travel-planner-64439.firebasestorage.app',
    iosBundleId: 'com.example.travelplanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-I14h8GjEskLdTpQVuhZTMwO8AAeDCLY',
    appId: '1:681145363568:ios:ef52fd977ae85b512ad8b5',
    messagingSenderId: '681145363568',
    projectId: 'travel-planner-64439',
    storageBucket: 'travel-planner-64439.firebasestorage.app',
    iosBundleId: 'com.example.travelplanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa-70dEY1SRRsJQK1UtuW0M8BaHmzYizs',
    appId: '1:681145363568:web:c728ed27377b07af2ad8b5',
    messagingSenderId: '681145363568',
    projectId: 'travel-planner-64439',
    authDomain: 'travel-planner-64439.firebaseapp.com',
    storageBucket: 'travel-planner-64439.firebasestorage.app',
    measurementId: 'G-DFRL1VC1FH',
  );
}
